project_id = "zlvptkwrehuoxvgwiurh"

[functions.chat]
verify_jwt = false

[functions.auto-close-orders]
verify_jwt = false

[functions.daily-report]
verify_jwt = false

[functions.wallet-alerts]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
